### ISSUE TITLE
This plugin is not working with linux.

### ISSUE THREAD

**Issue by thetoster** [UnluckyY1/flutter_downloads_folder#3]
Info on the readme is invalid. Method for linux is not implemented at all, and prevent compilation of whole application due to unused method warning

**Comment by UnluckyY1** [comment]
For Linux, the logic is implemented in pure Dart code. While I initially released it with Linux compatibility, I'm quite sure that I was able to compile it without any issues, I suspect there may have been a regression with recent updates. If you could share your Flutter doctor output and the logs, that would be super helpful.

**Comment by UnluckyY1** [comment]
> Info on the readme is invalid. Method for linux is not implemented at all, and prevent compilation of whole application due to unused method warning


I've made some potential fixes, but I'm unable to test them right now since I only have access to macOS and Windows machines. If you could test it from your side, that would be super helpful. Thank you for your report.


You can test by copying this to your **pubspec.yaml** file:

```
downloadsfolder:
    git: # fix linux compilation
      url: https://github.com/UnluckyY1/flutter_downloads_folder.git
      ref: "500f8a0"
```
